name: FirstJoinKits
version: '${project.version}'
main: cc.vastsea.firstjoinkits.FirstJoinKits
api-version: '1.18'
commands:
  firstjoinkits:
    aliases:
      - "fjk"
    description: "Plugin command."
    usage: "/firstjoinkits <sub command> [args]"
    permission: "firstjoinkits.command"
    permission-message: "You don't have the permission."

depend: [PlaceholderAPI]